// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfveigsnfatlmiiunprc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmdmVpZ3NuZmF0bG1paXVucHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNDEwOTksImV4cCI6MjA4NjYxNzA5OX0.fm5PwDgYWBhM8hWiyccyKx5ZstgN4-JS4chDPFvT1qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});